# 生成器

## 概述

* 生成器函数通过 `yield` 关键字来实现暂停执行和恢复执行
* 在处理异步任务时，可以更直观地处理异步操作，而无需嵌套回调函数或使用复杂的 `Promise` 链

## 创建

使用 `function* ` 来创建生成器函数，利用生成器函数可以创建生成器

箭头函数不能用于创建生成器函数

```js
function* generatorFn(){}
```

创建生成器：

* 直接赋给一个变量
* 作为对象的赋给一个变量
* 作为类的方法
* 作为类的静态方法

与迭代器一样，每个生成器都是独立的

```js
function* generatorFn() {
  yield 'foo';
  yield 'bar';
  return 'baz';
}

const generatorObject1 = generatorFn();
const generatorObject2 = generatorFn();


console.log(generatorObject1.next()); // { done: false, value: 'foo' }
console.log(generatorObject2.next()); // { done: false, value: 'foo' }
console.log(generatorObject2.next()); // { done: false, value: 'bar' }
console.log(generatorObject1.next()); // { done: false, value: 'bar' }
```



## `next()`

* 调用生成器会产生一个生成器对象，生成器对象一开始处于暂停执行状态

* 生成器对象实现了 `Iterable` 接口，具有 `next()` 方法，调用这个方法可以让生成器开始或恢复执行
* `next()` 方法的返回与迭代器类似
* `next()` 方法默认返回 `undefined`，可以在生成器内部指定

```js
function* generatorFn() {}

let generatorObject = generatorFn();

console.log(generatorObject);         // generatorFn {<suspended>}
console.log(generatorObject.next());  // { done: true, value: undefined }
```

```js
function* generatorFn() {
  return 'foo';
}

let generatorObject = generatorFn();

console.log(generatorObject);         // generatorFn {<suspended>}
console.log(generatorObject.next());  // { done: true, value: 'foo' }
```

## `yield`

* `yield` 可以让生成器停止执行，停止后，函数作用域保留，且 `done` 的值为 `false`
* 停止的生成器只能通过调用 `next()` 才能恢复执行
* `yield` 可以返回值，这个值被 `next()` 方法返回的 `value` 接收
* `return` 可以终止执行，终止后，函数作用域被销毁，且 `done` 的值为 `true`

```js
function* generatorFn() {
  yield 'foo';
  yield 'bar';
  return 'baz';
}

let generatorObject = generatorFn();

console.log(generatorObject.next());  // { done: false, value: 'foo' }
console.log(generatorObject.next());  // { done: false, value: 'bar' }
console.log(generatorObject.next());  // { done: true, value: 'baz' }
```

## 使用

与迭代器相同，显式地调用 `next()` 作用不大

### 当作可迭代对象

当作可迭代对象

```js
function* generatorFn() {
  yield 1;
  yield 2;
  yield 3;
}

for (const x of generatorFn()) {
  console.log(x);
}
// 1
// 2
// 3
```

```js
function* nTimes(n) {
  while(n--) {
    yield;
  }
}

for (let _ of nTimes(3)) {
  console.log('foo');
}
// foo
// foo
// foo
```

### 输入和输出

`next()` 可以接收一个值，这个值会被传递给上一个让生成器停止的 `yield`

```js
function* generatorFn(initial) {
  console.log(initial);
  console.log(yield);
  console.log(yield);
}

let generatorObject = generatorFn('foo');

generatorObject.next('bar');  // foo
generatorObject.next('baz');  // baz
generatorObject.next('qux');  // qux

/**
 执行流程：
 调用生成器函数创建生成器，initial 被赋值为 foo
 第一个 next()，函数打印 initial，然后遇到 yield，生成器停止
 第二个 next()，baz 被赋值给第一个 yield，打印 yield，遇到第二个 yield，生成器停止
 第三个 next()，qux 被赋值给第二个 yield，打印 yield，生成器终止
*/
```

因为 `yield` 和 `next()` 可以互相传值，`yeild` 可同时用于输入和输出

```js
function* generatorFn() {
  return yield 'foo';
}

let generatorObject = generatorFn();

console.log(generatorObject.next());       // { done: false, value: 'foo' }
console.log(generatorObject.next('bar'));  // { done: true, value: 'bar' }
```

### 产出可迭代对象

使用 `*` 增强 `yield` 将允许直接返回一个可迭代对象

```js
// 等价的 generatorFn：
// function* generatorFn() {
//   for (const x of [1, 2, 3]) {
//     yield x;
//   }
// }
function* generatorFn() {
  yield* [1, 2, 3];
}

let generatorObject = generatorFn();

for (const x of generatorFn()) {
  console.log(x);
}
// 1
// 2
// 3
```

### 实现递归

在传统的递归函数中，每次递归调用都会创建一个新的函数调用栈，如果递归层数过多，可能会导致栈溢出。而使用生成器实现递归，可以将递归操作转化为迭代过程，避免栈溢出的问题

```js
function* fibonacciGenerator(limit) {
  let prev = 0;
  let current = 1;
  yield prev;
  yield current;

  while (current + prev <= limit) {
    const next = current + prev;
    yield next;
    prev = current;
    current = next;
  }
}

// 使用生成器实现斐波那契数列的递归
const limit = 50;
for (const num of fibonacciGenerator(limit)) {
  console.log(num);
}
```

### 默认迭代器

生成器自带迭代器，可作为一个类的默认迭代器，而无需单独声明用于迭代的 `next()` 方法

```js
class Foo {
  constructor() {
    this.values = [1, 2, 3];
  }
* [Symbol.iterator]() {
    yield* this.values;
  }
}

const f = new Foo();
for (const x of f) {
  console.log(x);
}
// 1
// 2
// 3
```

## 提前停止迭代器

除了自带迭代器中的 `next()` 和 `return()` 方法，生成器还有 `throw()` 方法

### `return()` 

所有生成器的迭代器都有 `return()` 方法，且 `return()` 方法都能关闭迭代器

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x;
  }
}

const g = generatorFn();

console.log(g);            // generatorFn {<suspended>}
console.log(g.return(4));  // { done: true, value: 4 }
console.log(g);            // generatorFn {<closed>}
```

显式的调用 `return()` 后，生成器的迭代器被关闭

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x;
  }
}

const g = generatorFn();

console.log(g.next());     // { done: false, value: 1 }
console.log(g.return(4));  // { done: true, value: 4 }
console.log(g.next());     // { done: true, value: undefined }
console.log(g.next());     // { done: true, value: undefined }
console.log(g.next());     // { done: true, value: undefined }
```

### `throw()`

* 使用 `throw()` 可以向生成器内部注入一个 `exception`
* 如果 `exception` 未被处理，该 `exception` 会被抛回到注入它的上下文，且生成器的迭代器会被关闭

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    yield x;
  }
}

const g = generatorFn();

console.log(g);   // generatorFn {<suspended>}
try {
  g.throw('foo');
} catch (e) {
  console.log(e); // foo
}
console.log(g);   // generatorFn {<closed>}
```

错误处理会跳过一个 `yield`

```js
function* generatorFn() {
  for (const x of [1, 2, 3]) {
    try {
      yield x;
    } catch(e) {}
  }
}

const g = generatorFn();

console.log(g.next()); // { done: false, value: 1}
g.throw('foo');
console.log(g.next()); // { done: false, value: 3}
```